### ISSUE TITLE
Frontend is not setting up.

### ISSUE THREAD

**Issue by arpitnakrani** [idurar/erp-crm#303]
![image](https://github.com/idurar/idurar-erp-crm/assets/97463573/7907204a-cc8e-4696-92f3-231ec8616acc)

**Comment by arpitnakrani** [comment]
Followed exactly mentioned steps in readme and also tried deleting node modules.

**Comment by Abhishek7Tech** [comment]
@arpitnakrani
Hi navigate to frontend package.json and in start paste this "export NODE_OPTIONS=--openssl-legacy-provider && craco start" in place of "craco start".

 run npm run start

**Comment by arpitnakrani** [comment]
![image](https://github.com/idurar/idurar-erp-crm/assets/97463573/7cce8b21-33d1-46ed-a44b-5752895bea15)
@Abhishek7Tech not working

**Comment by sandeepV2** [comment]
@arpitnakrani 
The error is prompting you to update craco-less.

please try 
`npm update craco-less`

**Comment by polymahh** [comment]
@Abhishek7Tech i dont think this is the openssl issue here 
i think that you updated something in react 
can you show package.json for backend and frontend

**Comment by arpitnakrani** [comment]
FE :- {
  "name": "erp-crm",
  "version": "0.1.0",
  "engines": {
    "npm": "8.5.5"
  },
  "dependencies": {
    "@ant-design/icons": "4.7.0",
    "antd": "4.17.4",
    "axios": "0.27.2",
    "currency.js": "2.0.4",
    "dayjs": "1.10.4",
    "framer-motion": "4.1.13",
    "history": "4.10.1",
    "hoist-non-react-statics": "3.3.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-error-boundary": "3.1.3",
    "react-helmet": "6.1.0",
    "react-portal": "4.2.1",
    "react-redux": "7.2.8",
    "react-router-dom": "5.2.0",
    "react-scripts": "4.0.3",
    "react-use": "17.3.2",
    "redux": "4.2.0",
    "redux-logger": "3.0.6",
    "redux-thunk": "2.4.1",
    "reselect": "4.1.5",
    "web-vitals": "1.0.1",
    "@craco/craco": "5.5.0",
    "craco-alias": "3.0.1",
    "craco-less": "1.17.1",
    "cross-env": "7.0.3"
  },
  "scripts": {
    "start": "export NODE_OPTIONS=--openssl-legacy-provider && craco start",
    "start:dev": "cross-env REACT_APP_DEV_REMOTE=remote npm start",
    "build": "craco build",
    "dev:new": "cross-env npm start",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@testing-library/jest-dom": "5.16.1",
    "@testing-library/react": "12.1.2",
    "@testing-library/react-hooks": "7.0.2",
    "@testing-library/user-event": "13.5.0",
    "babel-plugin-import": "1.13.3",
    "identity-obj-proxy": "3.0.0",
    "prettier": "2.5.1",
    "redux-mock-store": "1.5.4"
  }
}


BE:- 
{
  "name": "idurar-backend",
  "version": "1.0.0",
  "engines": {
    "npm": "8.5.5",
    "node": "16.15.0"
  },
  "scripts": {
    "start": "node ./server.js",
    "dev": "nodemon ./server.js --ignore public/",
    "production": "NODE_ENV=production",
    "setup": "node ./setup/setup.js",
    "reset": "node ./setup/reset.js"
  },
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "dotenv": "4.0.0",
    "express": "^4.18.1",
    "glob": "7.1.1",
    "helmet": "^4.6.0",
    "html-pdf": "^3.0.1",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.20",
    "module-alias": "^2.2.2",
    "moment": "^2.26.0",
    "mongoose": "^6.3.3",
    "mongoose-autopopulate": "^0.14.0",
    "mongoose-sequence": "^5.2.2",
    "multer": "^1.4.2",
    "pug": "^3.0.2",
    "resend": "^0.17.2"
  },
  "devDependencies": {
    "nodemon": "^1.19.2"
  },
  "_moduleAliases": {
    "@": "."
  },
  "description": "Just you wait folks!",
  "main": "app.js",
  "keywords": [],
  "author": "Salah Eddine Lalami",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/idurar/idurar-erp-crm/.git"
  },
  "bugs": {
    "url": "https://github.com/idurar/idurar-erp-crm//issues"
  },
  "homepage": "https://github.com/idurar/idurar-erp-crm/#readme"
}


@polymahh be is working fine , and also i haven't updated any package.

**Comment by polymahh** [comment]
@arpitnakrani sorry for asking you these things ... but dont know any other way to debug this
but for some reason you dont have `currency.js` do a `git pull` on your `dev` branch and install BE and FE again

**Comment by arpitnakrani** [comment]
@polymahh its Be package.json , i dont think it will affect FE issue .

**Comment by polymahh** [comment]
@arpitnakrani my point is that you don't have the updated version of `dev`

**Comment by arpitnakrani** [comment]
okay i have cloned it 2 times yesterday @polymahh , i will fork it again and perform steps in readme again and let you know , BTW thank you for help

**Comment by anonymous4561** [comment]
try reinstalling node and npm version 
 "engines": {
        "node": "16.15.0",
        "npm": "8.5.5"
      }

**Comment by onfranciis** [comment]
@arpitnakrani if you're still having issues setting up the frontend, I recommend using the **dev:new** script. Let me know how it goes.

**Comment by polymahh** [comment]
@arpitnakrani was there a solution for your problem ?

**Comment by IvanBrazanovich** [comment]
I think your problem is that you are using 
`export NODE_OPTIONS=--openssl-legacy-provider`
 instead of 
`set NODE_OPTIONS=--openssl-legacy-provider`
Set is for windows. Export is for linux I think.

**Comment by dhrumitpatel48** [comment]
@IvanBrazanovich I have also faced this problem. Frontend is not setting up. 
Error is as above. 
Tried your solution but still there is error. 

@arpitnakrani Is this problem solved? I am facing same problem. Can you please help me to solved this error? 

I have tried everything that is mentioned in this conversation. 
Clone multiple times but still there is error. 

Someone please help.

**Comment by polymahh** [comment]
@dhrumitpatel48 try running this before starting the frontend 
`export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by dhrumitpatel48** [comment]
> @dhrumitpatel48 try running this before starting the frontend `export NODE_OPTIONS=--openssl-legacy-provider`

I'm using Windows machine. 
So export will not work in window
SET Will work on Windows machine. 

Even I have tried with Export, but it is not supported in Windows. So it throw error.

**Comment by polymahh** [comment]
if you tried  try SET does it fix the problem ? 
I am using windows too and i use Bash as terminal

**Comment by IvanBrazanovich** [comment]
Could you provide your error? You said:
 > Error is above
 But I don't see it, where is it?

**Comment by dhrumitpatel48** [comment]
> But I don't see it, where is it?

I was saying that I am facing the frontend error.

Here is screenshot
<img width="515" alt="image" src="https://github.com/idurar/erp-crm/assets/80308003/7a222f97-97bf-4092-bbdb-f778eb3991dd">

**Comment by dhrumitpatel48** [comment]
> But I don't see it, where is it?

<img width="727" alt="image" src="https://github.com/idurar/erp-crm/assets/80308003/6ac21404-6b59-48ea-bf30-b226ed033bbf">

**Comment by polymahh** [comment]
hello @dhrumitpatel48   did you fix it ? this is the openssl error you can fix it with 
`export NODE_OPTIONS=--openssl-legacy-provider`
are you using bash or Powershell ?

**Comment by dhrumitpatel48** [comment]
> hello @dhrumitpatel48 did you fix it ? this is the openssl error you can fix it with `export NODE_OPTIONS=--openssl-legacy-provider` are you using bash or Powershell ?

I'm using simple command line. In that command line I'm running all these setup commands. 

Backend setup has been done successfully. 

Frontend setup throws error. 

I have run NODE_OPTIONS=--openssl-legacy-provider this but above error message is throwing.

**Comment by IvanBrazanovich** [comment]
@dhrumitpatel48  See if something in the next thread works for you.
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by dhrumitpatel48** [comment]
> @dhrumitpatel48 See if something in the next thread works for you. https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

Thank you very much @IvanBrazanovich  This thread has solved my error. Thank you again.

**Comment by dhrumitpatel48** [comment]
> hello @dhrumitpatel48 did you fix it ? this is the openssl error you can fix it with `export NODE_OPTIONS=--openssl-legacy-provider` are you using bash or Powershell ?

My problem has been solved by this https://github.com/idurar/erp-crm/issues/303#issuecomment-1719710808.
 Thank you for your help.

**Comment by polymahh** [comment]
@dhrumitpatel48 maybe we need to update the readme with all different fixes for this issue

**Comment by dhrumitpatel48** [comment]
> @dhrumitpatel48 maybe we need to update the readme with all different fixes for this issue

Yes, it's good idea. 
I can do it. 
@salahlalami should I start this??
