### ISSUE TITLE
[FEAT]: Cache in the frontend 

### ISSUE THREAD

**Issue by OvilashMoitra** [idurar/erp-crm#314]
Every-time the api getting hit for not using caching.  RTK-Query or Tanstack Query(React Query) should use to cache the data.

**Comment by Vayras** [comment]
hi I would like to work on this issue

**Comment by polymahh** [comment]
@Vayras yes feel free to contribute

**Comment by OvilashMoitra** [comment]
yeah why not @Vayras  .

**Comment by Vayras** [comment]
@polymahh  @OvilashMoitra Could you kindly provide me with information regarding the specific files that are affected by this issue? I am currently finding the codebase to be a bit overwhelming
