### ISSUE TITLE
No state update when tryring to delete multiple invoice 

### ISSUE THREAD

**Issue by manziEric** [idurar/erp-crm#360]
When i delete 1 invoice the state of invoice component is updated, but when i try to delete a second invoice i get error
of memory leak and deleting a second invoice dont work any more.

<img width="1680" alt="Schermafbeelding 2023-08-27 om 19 03 08" src="https://github.com/idurar/idurar-erp-crm/assets/50232091/55f570d7-483d-4219-8d94-739a786977a7">
<img width="1680" alt="Schermafbeelding 2023-08-27 om 19 03 22" src="https://github.com/idurar/idurar-erp-crm/assets/50232091/cc93412f-fed8-41e8-8a42-8a7f4a51995f">

**Comment by polymahh** [comment]
@abhms yes feel free to contribute

**Comment by SahilAgrwl** [comment]
Plz assign this issue to me

**Comment by MassoudSharifi** [comment]
Hi @salahlalami 
Is someone already working on this bug, or can I fix it?
