### ISSUE TITLE
Create new Endpoint Offer CRUD Api , this almost similaire to Quote api

### ISSUE THREAD

**Issue by salahlalami** [idurar/erp-crm#390]
Offer are similaire to quote , just duplicate quote code.

Offer are for leads not for clients

**Comment by Vayras** [comment]
@salahlalami  I would like to contribute on this issue , can you please tell me the files associated with this issue? , so I can navigate through the project.

**Comment by salahlalami** [comment]
@Vayras start with this issue

**Comment by Ando22** [comment]
Hi @salahlalami @Vayras I already created this endpoint. it's already on `dev` branch at `routes/erpRoutes/erpApi.js`. feel free to test and improve the endpoint 👍

**Comment by sahith29s** [comment]
Can I start with this issue.

**Comment by polymahh** [comment]
hello @Ando22 is this issue already fixed ? if so feel free to close it

**Comment by salahlalami** [comment]
@Ando22 where is pr of this issue

**Comment by hassancode1** [comment]
> 

if there is no pr i would love to fix it

**Comment by Ando22** [comment]
This issue is solved by this [merged](https://github.com/idurar/erp-crm/pull/537)
