### ISSUE TITLE
feat : Create New Generic File Upload Controller

### ISSUE THREAD

**Issue by salahlalami** [idurar/erp-crm#412]
**Problem:**
There is a need to create a new generic file uploadController.js file with a model. This controller should be located inside the middlewaresControllers directory.

**Solution:**
To address this problem, the following steps need to be taken:

Create a new model named Upload within the coreModels directory. This model will have the following fields:

> modelName: The name of the model.
> fieldId: The ID of the field.
> enabled: A flag indicating whether the upload is enabled or not.
> isPublic: A flag indicating whether isPublic or protected.
> userID : userID who upload
> isSecure : if true , only users who upload can see  
> removed: A flag indicating whether the upload has been removed or not.
> path: The path to the uploaded file.

The File should upload to upload folder , inside modelName folder , the file should have a name of document id of (UploadCollection)

Add a new route to the coreRoutes file. This route should handle the URL pattern public/upload/:model/:fieldId.
Add a new route to the coreRoutes file. This route should handle the URL pattern private/upload/:model/:fieldId.

By following these steps, a new generic upload controller can be created with the necessary model and route structure.

**Comment by Aman-Gupta-404** [comment]
Hi @salahlalami, would love to work on this, but have a few questions

1. I believe I need to write the function to upload the files,so what type files are being uploaded
2. Is this route supposed to be protected?

if you could help me with this, I wold love to wrok on it

**Comment by salahlalami** [comment]
Hi @Aman-Gupta-404 

1- All standard types (image , pdf , docs)
2- if isPublic the route is not protected , otherwise is protected

**Comment by Aman-Gupta-404** [comment]
Great, I would love to work on this, can I create a PR?

I am thinking of using multer for file uploading, that should be fine right

**Comment by salahlalami** [comment]
@Aman-Gupta-404  waiting for your pr , yes we are using multer  right now

**Comment by salahlalami** [comment]
@IshaanShettigar you can pass id as params , this generic middleware ,
no need for multer.memoryStorage()

**Comment by pablo-codes** [comment]
So what about the auth middleware
We should create 1 that checks if isPublic or not???
