### ISSUE TITLE
[bug] pagination number item limit not working

### ISSUE THREAD

**Issue by OvilashMoitra** [idurar/erp-crm#446]
https://www.loom.com/share/4b76a6853608457ea766730a7d6b473c?sid=933df1c4-e279-48d8-ba7a-d688759e8430

Pagination ltem limit is fixed on 10 only not updating.

**Comment by MassoudFSharifi** [comment]
Hi @salahlalami,

I'm ready to contribute by fixing this bug. Should I go ahead and work on it?

**Comment by OvilashMoitra** [comment]
I have done working it.

**Comment by MassoudFSharifi** [comment]
> I have done working it.

ok
