### ISSUE TITLE
Notification Bug on demo site.

### ISSUE THREAD

**Issue by NogueiraDan** [idurar/erp-crm#463]
There is an issue with the notification dropdown. By clicking on the remove icon from the latest notifications, they are deleted. But when you click on the first ones called "Third" it makes the removed notifications appear. 
On the demo site: https://demo-erp-crm.idurarapp.com/

**Comment by Sinharitik589** [comment]
This is also the problem when running the app locally . @onfranciis @NogueiraDan Can you assign me this issue .
