### ISSUE TITLE
Not able to update payment invoice

### ISSUE THREAD

**Issue by Sinharitik589** [idurar/erp-crm#484]
**Describe the bug**
I am not able to update payment invoice
**Additional context**
The major issue here is that the page for updating payment invoice renders same component as for updating invoice and with no additional fields related to the payment invoice like payment mode etc . Rather it should display the payment invoice options . Is there any part i am missing here like any additional feature @onfranciis @polymahh @salahlalami .

**Comment by 18feb06** [comment]
@Sinharitik589 This issue has been resolved. Kindly try again.
