### ISSUE TITLE
feat : Responsive Recent Invoice / Quote in Dashboard 

### ISSUE THREAD

**Issue by salahlalami** [idurar/erp-crm#488]
make Recent Invoice / Quote responsive in Dashboard 

<img width="585" alt="Screenshot 2023-09-08 at 8 11 05 PM" src="https://github.com/idurar/idurar-erp-crm/assets/136928179/fde5586e-ff11-4e22-8784-e093db6d3441">

**Comment by Vishrut19** [comment]
Hey @polymahh Are you working on it? Or I can take up this issue?
