### ISSUE TITLE
Add payment mode redirect description

### ISSUE THREAD

**Issue by parteekcoder** [idurar/erp-crm#496]
**Is your feature request related to a problem? Please describe.**
If the user does not have any payment method on this page , he might not know from where to add one.

![image](https://github.com/idurar/erp-crm/assets/100110395/0c1534f3-662e-4562-a97e-36d288882531)

**Describe the solution you'd like**
So below this input there should be a small hyper text to redirect the user to that page like `add payment method`

**Comment by himanshumalviya15** [comment]
@salahlalami What is your call on this feature

**Comment by DecodeAndCode** [comment]
I started working on it @parteekcoder

**Comment by salahlalami** [comment]
@parteekcoder , inside this component , if it empty , will link inside it as select option to redirect to add new payment mode
