### ISSUE TITLE
Delete button on Recent invoices and Recent Quotes dont work

### ISSUE THREAD

**Issue by Sinharitik589** [idurar/erp-crm#500]
**Describe the bug**
Delete button on the Recent invoices and Recent Quotes section doesn't work

**To Reproduce**
1. Open Dashboard
2. Click on more section "..." on recent invoices
3. Select Delete

**Expected behavior**
Delete option should open a dialogue box for deletion

**Screenshots**
![ezgif com-video-to-gif (13)](https://github.com/idurar/erp-crm/assets/67551927/6e0a6164-5df6-45bd-b50c-464e14d4f564)

**Comment by MassoudSharifi** [comment]
@salahlalami assign this to me I will fix

**Comment by Sinharitik589** [comment]
@MassoudSharifi i am already working on it .
