### ISSUE TITLE
issue: search is not working correctly

### ISSUE THREAD

**Issue by polymahh** [idurar/erp-crm#511]
we need to fix the search component 
1 - go to invoice > click add new invoice > search for a client
the result should be the names containing "s"

![image](https://github.com/idurar/erp-crm/assets/15654652/158aba4e-8df7-4e91-b5eb-8fe49ce464d4)

2-  after searching the first time click outside input and try to search again 
search does not show any results 

![image](https://github.com/idurar/erp-crm/assets/15654652/50ddb961-61a1-4522-a989-686a3716cd5f)

**Comment by Sinharitik589** [comment]
@polymahh i want to work on it . please assign me

**Comment by salahlalami** [comment]
@polymahh  @Sinharitik589 , to fix it update InvoiceForm: 

`    <AutoCompleteAsync
              entity={'client'}
              displayLabels={['company']}
              searchFields={'company'}
            />`

please do same in quote

**Comment by polymahh** [comment]
@Sinharitik589 pls always start from dev and update it before branching

**Comment by Sinharitik589** [comment]
@salahlalami what about customer panel , it also search based on managerSurname and managerName ..Can we write a placeholder stating Search Company or Manager or should it be based on only company.
