### ISSUE TITLE
Bug : in Backend Remove payment record after we remove invoice

### ISSUE THREAD

**Issue by salahlalami** [idurar/erp-crm#514]
**Describe the bug**
When we remove invoice their payment record still appear in paymentInvoive collection

**Solution** 
1- in invoiceController ovveride delete method , after remove invoice sucess , search for their payment record and delete them logically : 
```

  const result = await Model.findOneAndUpdate(
      { _id: req.params.id, removed: false },
      { $set: {
      removed: true,
    } },
      {
        new: true, // return the new result instead of the old one
      }
    ).exec();

 

```

**Comment by codewithvk** [comment]
Can i work on this issue?
