### ISSUE TITLE
Bug : Backend we can't remove client if they have at least one invoice or one quote

### ISSUE THREAD

**Issue by salahlalami** [idurar/erp-crm#515]
Describe the bug
we can't remove client if they have at least one invoice or one quote

Solution
1- in clientController override delete method , before remove client , check if they have at least one invoice or one quote

**Comment by mustachemo** [comment]
hello, I don't see a delete method in clientController.js.

**Comment by salahlalami** [comment]
@mustachemo it use middlewareController methods , you just need to override :

`methods..delete =   async (req, res) => { .... } `

**Comment by Zewenaco** [comment]
Hello, I'd like to contribute to the project, can I be assign to this one?

**Comment by salahlalami** [comment]
you are welcome to contribute @Zewenaco

**Comment by AIABHISHEK** [comment]
If no one is working on this issue @salahlalami can you assign me I will start working on this.

**Comment by salahlalami** [comment]
@AIABHISHEK sure , you can work on it
