### ISSUE TITLE
Invoice table doesn't remove row after been deleted when there is only one row

### ISSUE THREAD

**Issue by Zewenaco** [idurar/erp-crm#520]
**Describe the bug**
Table doesn't remove row after been deleted when there is only one row

**To Reproduce**
1. Go to Invoice, delete all records until have a single one
2. Delete the last one
3. After successfull message, the row still there
4. Try to update the row with button Refresh, and still would be there
5. That's the error

**Expected behavior**
All rows should be remove when there were deleted

**Screenshots**
![Captura de pantalla 2023-09-14 111522](https://github.com/idurar/erp-crm/assets/12084834/a89ac3c3-a3f2-4f29-9d45-de5aaccacd2f)

![Captura de pantalla 2023-09-14 120443](https://github.com/idurar/erp-crm/assets/12084834/9943b5f5-fcc1-4895-8821-6db6ab905375)

![Captura de pantalla 2023-09-14 120450](https://github.com/idurar/erp-crm/assets/12084834/033a013e-a955-45a0-b29d-7a22df5c7d0f)

![Captura de pantalla 2023-09-14 120457](https://github.com/idurar/erp-crm/assets/12084834/508ea55c-48c2-44ce-aac5-60332254481d)

![Captura de pantalla 2023-09-14 120505](https://github.com/idurar/erp-crm/assets/12084834/623204ea-46b2-4327-9448-b3094ff24e71)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 116.0.5845.188 (Build oficial) (64 bits)

**Comment by Sinharitik589** [comment]
@ its the backend issue 
https://github.com/idurar/erp-crm/blob/e670d2830d08b0c0b80d884f031f50b056cb075a/controllers/middlewaresControllers/createCRUDController/listAll.js#L17-L22

Whenever no invoice is there we are sending success as false .

**Comment by Sinharitik589** [comment]
> Thanks for the reply, considering the code that you're mention. In my experience when an endpoint is returning a list or a pageable of element, if it's empty it should return success and the empty result. In this case, the backend return successfully ( an empty ) but yet successfully;
> 
> Should we refactor this to return another http code or just change the sucess value? WDYT? It could be more suitable if the method return 204 in case of empty collection?

In my view status code is current , succes needs to refactor as we are refferencing only succes here
https://github.com/idurar/erp-crm/blob/e670d2830d08b0c0b80d884f031f50b056cb075a/frontend/src/redux/erp/actions.js#L47-L66

**Comment by salahlalami** [comment]
@Zewenaco Thank your for report , issue fixed
