### ISSUE TITLE
Frontend : create a new email editor template settings page

### ISSUE THREAD

**Issue by salahlalami** [idurar/erp-crm#548]
![react-js-developers-create-a-email-editor-template-by-using-react-quill](https://github.com/idurar/erp-crm/assets/136928179/dece0237-6dad-4bc6-b534-25fdc426aef2)

need to create a new email template settings page that allows users to edit email templates using the react-quill library. This library provides a rich text editor component for React applications. The goal is to use react-quill to allow users to modify the message content of an email template.

The email template settings page should provide a user interface where users can see and edit the email template. The react-quill ([https://github.com/zenoamaro/react-quill](https://github.com/zenoamaro/react-quill)) component will be used as the editor for the email template message.

The email template message should be saved in the settings so that it can be retrieved and used later when sending emails. It is important to ensure that the updated template message is properly saved and associated with the correct email template.

### Additional context
Additionally, this page should support editing multiple templates. This means there should be a way to switch between different email templates and update their respective message content using the react-quill editor.

By following these guidelines, you can create a fully functional email template settings page that allows users to customize and save email templates using the react-quill library.

### Settings Api
```javascript

router.route('/setting/listAll').get(catchErrors(settingController.listAll));
router.route('/setting/filter').get(catchErrors(settingController.filter));
router
  .route('/setting/readBySettingKey/:settingKey')
  .get(catchErrors(settingController.readBySettingKey));
router.route('/setting/listBySettingKey').get(catchErrors(settingController.listBySettingKey));
router
  .route('/setting/updateBySettingKey/:settingKey?')
  .patch(catchErrors(settingController.updateBySettingKey));
router.route('/setting/updateManySetting').patch(catchErrors(settingController.updateManySetting));
```

### Settings Key
```javascript
[
  {
    "settingKey": "email_invoice_default",
    "settingValue": "<p>email_invoice_default</p>",
    "valueType": "string",
    "isCoreSetting": true
  },
  {
    "settingKey": "email_quote_default",
    "settingValue": "<p>email_quote_default</p>",
    "valueType": "string",
    "isCoreSetting": true
  },
  {
    "settingKey": "email_offer_default",
    "settingValue": "<p>email_offer_default</p>",
    "valueType": "string",
    "isCoreSetting": true
  },
  {
    "settingKey": "email_payment_receipt_default",
    "settingValue": "<p>email_offer_default</p>",
    "valueType": "string",
    "isCoreSetting": true
  },
  {
    "settingKey": "email_signup_email_confirm_default",
    "settingValue": "<p>email_signup_email_confirm</p>",
    "valueType": "string",
    "isCoreSetting": true
  },
  {
    "settingKey": "email_reset_password_default",
    "settingValue": "<p>email_reset_password</p>",
    "valueType": "string",
    "isCoreSetting": true
  },
  {
    "settingKey": "welcome_email_default",
    "settingValue": "<p>welcome_email</p>",
    "valueType": "string",
    "isCoreSetting": true
  }
]

```

**Comment by OvilashMoitra** [comment]
@salahlalami please check
My Get from requirement:

1. all template will be saved in Database
2. and will be shown like this where there will be a button to edit.
3. when click on the edit quill editor will open and after save it will save and sync with the database and then
4. all template will be shown

Am I supposed do only the frontend part?
I have made some thing like this.Can you please look at this and give me if anything need to change or if I get the requirement wrong.
https://www.loom.com/share/c53a979ea7c14cab96b1e02bcee7afd1?sid=28e3ccc4-f160-40e3-b630-88a3b98e3d09

**Comment by rcypankaj** [comment]
Hlo Dear, I would like to work on this issue please assign it to me!
